### ISSUE TITLE
control highlighting style?

### ISSUE THREAD

**Issue by friendly** [shafayetShafee/line-highlight#19]
`line-highlight` seems to work by downlighting all the non-highlight lines. Is it possible to change this behaviour, eg leave other lines alone, but

* print highlight lines **in bold**
* print highlight lines in color

As it is, this is not very useful, particularly with a (default) gray background for code blocks

**Comment by shafayetShafee** [comment]
Yes, It's possible. Just disable the syntax highlighting and then tweak the css for line highlighting.

**style.css**

``` css
body:not(.modal-open) div.sourceCode 
pre code.has-line-highlights > span.highlight-line {
  color: red;
  font-weight: 900;
}
```

~~~
---
title: "line highlighting"
format: html
css: style.css
highlight-style: "null"
filters:
  - line-highlight
---

```{r}
#| message: false
library(dplyr)

iris |>
  group_by(Species) |> #<<
  summarize(mean(Sepal.Length)) 
```
~~~


![image](https://github.com/shafayetShafee/line-highlight/assets/48413872/c1c7ed5c-5da5-43f3-807c-1e11c2875dcb)
